Появился хамонд
AndreiZaycev/CalculatorFSharp pull request #3
Opened 2021-04-27 19:16 UTC by AndreiZaycev

2021-04-29 07:45 UTC, gsvgit requested changes
Ридми пусте, ссылки на сайт нету, описания проекта нету, автоматически генерируемой документации для кода нету.

2021-04-29 07:45 UTC, gsvgit commented on docs/index.md
> +This calculator was created to evaluate expressions using the F # language.
Что за выражения? Расскажите чуть подробнее.

2021-04-29 07:45 UTC, gsvgit commented on src/CalculatorFSharp/BigAriphmetics.fs
> +// добавляет 0 впереди числа
А почкму бы не делать сразу нормальные комментарии, которые потом в докуентации будут отображаться.

2021-04-29 08:38 UTC, gsvgit requested changes
Ссылка на сайт не работает.
Ссылки в описании репозтория нету.
В ридми нету
- Статуса сборки
- Требований к сборке
- Структуры репозитория
- Имеющееся описание, честно говоря, "так себе". И по содержанию и по языку.

2021-05-05 16:50 UTC, gsvgit commented
Почему здесь пусто?
![Screenshot from 2021-05-05 19-48-51](https://user-images.githubusercontent.com/106816/117178811-19f71b80-addb-11eb-98cb-818a41c8a514.png)

2021-05-05 16:52 UTC, gsvgit commented
Вы мой вот этот комментарий читали? https://github.com/AndreiZaycev/CalculatorFSharp/pull/3#pullrequestreview-647948348

А на пример репозитория смотрели?

2021-05-05 17:49 UTC, AndreiZaycev commented
Да комментарий читал и примеры репо, забыл вывести в about и билды что то в ридми поломанные, диаграмму пока сдавать не буду

2021-06-03 09:38 UTC, AndreiZaycev commented
Ридми переделано по шаблону, диаграмму пока не сдаю

2021-06-04 06:16 UTC, gsvgit approved these changes
Норм. С тысячной попытки, но шаблоны делают своё дело.

2021-06-04 09:12 UTC, merged